default:
    @just --list --unsorted

# Demo assets stay outside <plugin>/: install ships that entire dir.
demo_root := justfile_directory() / "_demo"

# Point herdr's config, registry, and sockets at _demo/, not your real setup.
export XDG_CONFIG_HOME := demo_root / ".config"
export XDG_STATE_HOME := demo_root / ".local/state"

# The yazi-popup tape uses this sample repo as its file tree. Generated by
# `demo-repo`, not committed -- see _demo/fixtures/sample-repo for the baseline.
demo_repo := demo_root / ".sample-repo"
export DEMO_SAMPLE_REPO := demo_repo

# This shell can run inside a herdr pane, which sets HERDR_SOCKET_PATH to your
# real, live socket. Each recipe clears it first, so XDG isolation applies.
unset_pane_env := "unset HERDR_SOCKET_PATH HERDR_CLIENT_SOCKET_PATH HERDR_ENV HERDR_PANE_ID HERDR_WORKSPACE_ID HERDR_TAB_ID HERDR_STARTUP_CWD HERDR_BIN_PATH"

# Link a plugin into the isolated demo config: just link yazi-popup
[group('demo')]
link plugin:
    #!/usr/bin/env sh
    set -eu
    {{ unset_pane_env }}
    cd {{ justfile_directory() }}/{{ plugin }}
    herdr plugin link "$(pwd)"

# Rebuild DEMO_SAMPLE_REPO from the checked-in fixture.
[group('demo')]
demo-repo:
    #!/usr/bin/env sh
    set -eu
    rm -rf {{ demo_repo }}
    cp -R {{ demo_root }}/fixtures/sample-repo {{ demo_repo }}
    cd {{ demo_repo }}
    git init -q -b main
    git add .
    git commit -q -m "init sample repo"

# Record the yazi-popup demo: just vhs yazi-popup picker.tape
# --session resumes its last saved cwd instead of the tape's `cd`, so each
# session gets stopped and wiped first: every recording starts clean, and
# stopping before wiping means `server stop` can still reach the socket
# (a server left running after its socket is deleted can't be stopped).
[group('demo')]
vhs plugin tape: demo-repo
    #!/usr/bin/env sh
    set -eu
    {{ unset_pane_env }}
    stop_all_sessions() {
        for s in "{{ demo_root }}/.config/herdr/sessions"/*/; do
            [ -d "$s" ] || continue
            herdr --session "$(basename "$s")" server stop 2>/dev/null || true
        done
    }
    stop_all_sessions
    rm -rf "{{ demo_root }}/.config/herdr/sessions"
    cd {{ demo_root }}/{{ plugin }}
    vhs {{ tape }}
    stop_all_sessions
